repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict # Check for files that contain merge conflict strings
  - id: check-yaml # Attempts to load all yaml files to verify syntax
  - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
  - id: trailing-whitespace # Trims trailing whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.5
  hooks:
    - id: ruff
      verbose: true
    - id: ruff-format

- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: uv run mypy .
      language: system
      types: [python]
      pass_filenames: false
